### ISSUE TITLE
Error when running Testing Kinetics: no is_shift defined in TSN()

### ISSUE THREAD

**Issue by caidonkey** [MCG-NJU/TDN#1]
Thanks for sharing the codes.

I tried to evaluate TDN-ResNet50-8x3x10 in your model zoo on Kinetics following your examples:

> CUDA_VISIBLE_DEVICES=0 python3 test_models_three_crops.py  kinetics \
> --archs='resnet50' --weights <your_checkpoint_path>  --test_segments=8 \
> --test_crops=3 --batch_size=16 --full_res --gpus --output_dir <your_pkl_path>  \
> -j 4 --clip_index <your_clip_index>

Error occurs when constructing TSN (Line 124 in test_models_three_crops.py):

>     net = TSN(num_class, this_test_segments, modality,
>               base_model=this_arch,
>               consensus_type=args.crop_fusion_type,
>               img_feature_dim=args.img_feature_dim,
>               pretrain=args.pretrain,
>               is_shift=is_shift, shift_div=shift_div, shift_place=shift_place
>               )

There is no is_shift, shift_div and shift_place defined for TSN(nn.module) in ops/models.py. 
Maybe you need to update ops/models.py?

**Comment by yztongzhan** [comment]
@caidonkey Sorry, we have updated the test code, you can try the same test scripts again.
