### ISSUE TITLE
suggestion:added function

### ISSUE THREAD

**Issue by mytk2012** [MCG-NJU/TDN#10]
**visualization tools:**grad-cam

**Comment by yztongzhan** [comment]
Hi @mytk2012! Thanks for your nice suggestion. We already have the plan to merge our TDN into [MMaction2](https://github.com/open-mmlab/mmaction2), which supports many [demos](https://github.com/open-mmlab/mmaction2/tree/master/demo), including the GradCAM Demo. Please wait for a few days.
