### ISSUE TITLE
Confusion about frames sampling

### ISSUE THREAD

**Issue by AllenM97** [MCG-NJU/TDN#11]
Hi, your paper shows you set frames sampling number T=8, 16 and 8+16 respectively, and what does the "8+16" mean? Is it an ensemble of two models or just a simple setting that T=24? I have some trouble in understanding "8+16" and I don't know how to rerive this result.

**Comment by yztongzhan** [comment]
Hi @AllenM97, the "8+16" in our paper is indeed an ensemble of two models like [TSM](https://arxiv.org/abs/1811.08383) and [TEINet](https://arxiv.org/abs/1911.09435).
