### ISSUE TITLE
Kinetics400 data

### ISSUE THREAD

**Issue by MartinXM** [MCG-NJU/TDN#12]
Hi, @yztongzhan nice work! Can you share your version of kinetics400 with me? My current version is similar to @caidonkey in #2 , with short side equals 256. My email address is marquezxm@gmail.com. Many thanks !

**Comment by caidonkey** [comment]
I thinke it would be more reasonable for you to obtain the original Kinetics dataset and preprocess it as needed. It takes forever to transmit the extracted frames online since it's too huge with too many small files.

**Comment by yztongzhan** [comment]
Hi, @MartinXM! It's too difficult for us to share such large dataset. 
However, I recommend you to try this local copy from [this direct link](https://github.com/youngwanLEE/VoV3D/blob/main/DATA.md#kinetics-400) or download kinetics400 and kinetics700 from [Academic Torrents](https://academictorrents.com/details/184d11318372f70018cf9a72ef867e2fb9ce1d26). Thanks!
