### ISSUE TITLE
GradCAM code

### ISSUE THREAD

**Issue by sudonto** [MCG-NJU/TDN#15]
Hi, thanks for the code.
Could you share the code implementation of GradCAM? I know there are gradcam available in the Internet but it would be nice if you could also publish it in this repo.

**Comment by yztongzhan** [comment]
Hi @sudonto! Thanks for your nice suggestion. We already have the plan to merge our TDN into [MMaction2](https://github.com/open-mmlab/mmaction2), which supports many [demos](https://github.com/open-mmlab/mmaction2/tree/master/demo), including the GradCAM Demo. Please wait.
