### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by AllenM97** [MCG-NJU/TDN#16]
Hi, I run the following testing scripts
 `CUDA_VISIBLE_DEVICES=1 python test_models_center_crop.py something --archs='resnet50' --weights checkpoints/best.pth.tar --test_segments=8 --test_crops=1 --batch_size=16 --gpus 0 --output_dir output/8f -j 4 --clip_index=0` 
in which the `best.pth.tar` is downloaded from your sthv1 model zoo, but I got the results that `Overall Prec@1 0.22% Prec@5 2.40%`.
I wonder what mistakes might I make...

**Comment by yztongzhan** [comment]
Can you provide more information? Where is the `best.pth.tar` in your local machine?

**Comment by AllenM97** [comment]
> Can you provide more information? Where is the `best.pth.tar` in your local machine?

I downloaded the `best.pth.tar` from your `Model Zoo` and I created a folder named checkpoints in the root and then put the `best.pth.tar` in this folder.

**Comment by yztongzhan** [comment]
Oh @AllenM97  , I konw the question. Because your annotations is different from ours. We use this [scipts](https://github.com/mit-han-lab/temporal-shift-module/blob/master/tools/gen_label_sthv1.py) to generate the annotations.

**Comment by AllenM97** [comment]
> Oh @AllenM97 , I konw the question. Because your annotations is different from ours. We use this [scipts](https://github.com/mit-han-lab/temporal-shift-module/blob/master/tools/gen_label_sthv1.py) to generate the annotations.
Do you mean the first item in each line of annotation.txt contains the path? If it does, I already changed the txt correctly, otherwise it cannot even run the code...Or are there some other differences that matter?

**Comment by AllenM97** [comment]
> Oh @AllenM97 , I konw the problem. Because your annotations is different from ours. We use this [scipts](https://github.com/mit-han-lab/temporal-shift-module/blob/master/tools/gen_label_sthv1.py) to generate the annotations.

Do you mean the first item in each line of annotation.txt contains the path? If it does, I already changed the txt correctly, otherwise it cannot even run the code...Or are there some other differences that matter?

**Comment by AllenM97** [comment]
![image](https://user-images.githubusercontent.com/26690595/114522023-861baf00-9c75-11eb-81ca-99c1094f04a5.png)
And this is the screenshot of my result.

**Comment by yztongzhan** [comment]
Your annotations is different from ours. For example, one class "xxxx" is 100 in our annotation file while 99 in yours.

**Comment by AllenM97** [comment]
> Your annotations is different from ours. For example, one class "xxxx" is 100 in our annotation file while 99 in yours.

Thank you for quick responce!
