### ISSUE TITLE
train on kinetics 

### ISSUE THREAD

**Issue by user8361** [MCG-NJU/TDN#18]
Hi , thanks for sharing this code .
I want to ask is there anyone who trained this code on kinetics datasets . I have generated annotations followed by introductions, but got some errors . And i found that the generated file（train.txt and val.txt） doesn't match to the code in datasets.py .

**Comment by yztongzhan** [comment]
Hi @user8361, We decode the video on-the-fly for kinetics.

**Comment by yztongzhan** [comment]
Hi @user8361, we have given more details for Kinetics Data Preparation in `README.md`. If you don't have more question, I will close this issue.

**Comment by yztongzhan** [comment]
> I want to ask is there anyone who trained this code on kinetics datasets .
