### ISSUE TITLE
finetune训练加载模型something_resnet50_segment8/best.pth.tar时报错

### ISSUE THREAD

**Issue by BaronLeeLZP** [MCG-NJU/TDN#21]
你好同学，在测评TSM和TDN时进行fine-tuning训练，本项目加载预训练模型报错Notice: keys that failed to load:{'module.base_model.layer2_bak.1.bn1.running_var', 'base_model.layer4_bak.0.bn1.weight', 'module.new_fc.weight', 'base_model.layer1_bak.1.conv2.bias', 'module.base_model.layer2_bak.1.bn3.running_var', ......如何解决？谢谢！
另，resume训练时修改加载函数参数可以正常训练。

**Comment by yztongzhan** [comment]
you can try these code to load the checkpoint and finetune the model.

    checkpoint = checkpoint['state_dict']
    base_dict = {'.'.join(k.split('.')[1:]): v for k, v in list(checkpoint.items())}
    replace_dict = {'base_model.classifier.weight': 'new_fc.weight',
                    'base_model.classifier.bias': 'new_fc.bias',
                    }
    for k, v in replace_dict.items():
        if k in base_dict:
            base_dict[v] = base_dict.pop(k)
    net.load_state_dict(base_dict)
