### ISSUE TITLE
questions about ShiftModule used in BottleneckShift

### ISSUE THREAD

**Issue by ZGCTroy** [MCG-NJU/TDN#23]
Thanks for sharing the code !

I find the ShiftModule which uses a conv1d to shift like TSM.  In your BottleneckShift, you add a mSEModule and ShiftModule, making it different from the normal Bottleneck. 

Does the mSEMoudle refer to Long-term TDM in your paper? How about the ShiftModule, does the ShiftModule refer to the shift module of TSM. 

'''
   out = self.mse(out)        
   out = self.shift(out
'''
In your code, you simultaneously applied the mse and shift. Does this mean the TDM simultaneously use L-TDM and TSM shift ? Or you just set ShiftModule(mode = 'fixed') when running TDM.

**Comment by yztongzhan** [comment]
Hi @ZGCTroy, Thanks for your comments.
1. Yes! The mSEMoudle refer to Long-term TDM in your paper.
2. We use the ShiftModule is a 1D-Conv which is followed by TEA. you can refer the original TEA paper for more detail.
3. As shown in the figure 2 of our paper, we add the 1D-Conv after L-TDM. And, our baseline is  ResNet with 1D temporal convolutions in latter stages for better temporal modeling.
