### ISSUE TITLE
What's the meaning of Frames, Crops, and Clips reqpectvely?

### ISSUE THREAD

**Issue by SCZwangxiao** [MCG-NJU/TDN#25]
Hi, I am currently applying your method for very large-scale micro-video classification.
However, I am a little confused about the ``Frames``, ``Crops``, and ``Clips`` in your paper, since I am a green hand.
May I check their meanings with you?
 - ``Frame``: the number of segments sampled from a video, and a segment may have lots of frames?
 - ``Crop``: the number of cropped images in a single frame?
 - ``Clip``: I don't know. It cannot be the number of frames in a segment because i's fixed to 5?

**Comment by yztongzhan** [comment]
1. You are right.
2. You are right. `3 crops` is  just used during **testing** Kinetics 400.
3.  Here `Clip` means 'perfom testing for 10 times' which has been mentioned in the  `README` [here](https://github.com/MCG-NJU/TDN#testing)
