### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by LV0913** [MCG-NJU/TDN#27]
Thanks for sharing the code. After downloading pretrained models, I found that the files is damaged and can not be used. Please check and provide available models.Thanks!

**Comment by yztongzhan** [comment]
Thanks for your reply. Which one is damaged, can you provide the errror information?

**Comment by LV0913** [comment]
I downloaded all models. Errors are reported when decompressing all models. The error content is that the data is damaged.

**Comment by LV0913** [comment]
The specific error:
`tar:它似乎不像是一个tar归档文件
tar:跳转到下一个头
tar:由于前次错误，将以上次错误退出`
 The commend is tar -xf best.pth.tar

**Comment by yztongzhan** [comment]
hmmm....
I recommend you to learn how to  load pretrained model [here](https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-and-loading-models).

**Comment by yztongzhan** [comment]
`torch.load('best.pth.tar')` is all you need :)

**Comment by LV0913** [comment]
HH, sorry for the stupid question. I haven't used torch for a long time, so I ignored this. Thank you for your help !
