### ISSUE TITLE
Question about processing of HMDB51 dataset

### ISSUE THREAD

**Issue by MonkeyKing-KK** [MCG-NJU/TDN#29]
Hi, I'm trying to fine-tune on HMDB51, but I have no idea about how u cope with this .avi dataset and its corresponding annotation format.  Can you help on this? Thanks a lot.

**Comment by yztongzhan** [comment]
Please refer the [TSN](https://github.com/yjxiong/tsn-pytorch) and [TSM](https://github.com/mit-han-lab/temporal-shift-module) codebase for more details.
