### ISSUE TITLE
where is the short term TDM part?

### ISSUE THREAD

**Issue by Holmes-GU** [MCG-NJU/TDN#3]
Hi, thank your for sharing codes.
I am reading your code and I only find the long term TDM as mentioned in the paper in base_module.py and the short term TDM is not found, so where is it?

Thank you very much.

**Comment by yztongzhan** [comment]
Thanks for your comments, we implement S-TDM in `ops/tdn_net.py`  as mentioned in the README.
https://github.com/MCG-NJU/TDN/blob/170f380317d77f6f8a418153df43a02b58f88120/ops/tdn_net.py#L14

**Comment by Holmes-GU** [comment]
> Thanks for your comments, we implement S-TDM in `ops/tdn_net.py` as mentioned in the README.
> 
> https://github.com/MCG-NJU/TDN/blob/170f380317d77f6f8a418153df43a02b58f88120/ops/tdn_net.py#L14

ok, thank you

**Comment by YanjunChen** [comment]
> Hi, thank your for sharing codes.
> I am reading your code and I only find the long term TDM as mentioned in the paper in base_module.py and the short term TDM is not found, so where is it?
> 
> Thank you very much.

Did you find the code for long range TDM? Thanks

**Comment by Holmes-GU** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        The short term TDN part is in the tdn_net.py.
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ellery-holmes
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 6/9/2021 ***@***.***> wrote： 




Hi, thank your for sharing codes.
I am reading your code and I only find the long term TDM as mentioned in the paper in base_module.py and the short term TDM is not found, so where is it?
Thank you very much.

Did you find the code for long range TDM? Thanks

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by YanjunChen** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } The short term TDN part is in the tdn_net.py. ellery-holmes ***@***.*** 签名由 网易邮箱大师 定制 On 6/9/2021 ***@***.***> wrote： Hi, thank your for sharing codes. I am reading your code and I only find the long term TDM as mentioned in the paper in base_module.py and the short term TDM is not found, so where is it? Thank you very much. Did you find the code for long range TDM? Thanks —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks!
