### ISSUE TITLE
When testing on sth-sth-v1, which checkpoint should be used, 'best.pth' or '60_epoch_ckpt_pth'?

### ISSUE THREAD

**Issue by withbrightmoon** [MCG-NJU/TDN#31]
Hi, I train TDN-ResNet50 on Something-Something-V1. I find that the testing result of 'best.pth' is about 
0.5% better than that of  '60_epoch_ckpt_pth', the checkpoint of the last epoch. So which one should I use when testing?

I'll appreciate that if someone can help me.

**Comment by yztongzhan** [comment]
Hi @withbrightmoon, you can try the best one for testing.

**Comment by withbrightmoon** [comment]
Thanks!
