### ISSUE TITLE
Visualization wtih Grad-CAM

### ISSUE THREAD

**Issue by wei666666** [MCG-NJU/TDN#35]
Hi! Thank you for your wonderful project! I've tried to visualization with gradcam, and the results are as follows.

![800_7_gradcam_cam](https://user-images.githubusercontent.com/52570733/130166517-5fdaebed-bc48-44f1-baa9-e2c970fac1d7.jpg)![800_10_gradcam_cam](https://user-images.githubusercontent.com/52570733/130166523-a04d9527-dbaf-4c8a-b4b1-51964ac0915e.jpg)![800_19_gradcam_cam](https://user-images.githubusercontent.com/52570733/130166534-72849a7d-0244-4e9a-8552-f1a6ce204443.jpg)![800_32_gradcam_cam](https://user-images.githubusercontent.com/52570733/130166537-9d4a0e53-2168-4db6-b6bf-98cb87058e78.jpg)
![800_36_gradcam_cam](https://user-images.githubusercontent.com/52570733/130166542-084d474e-f2c5-4132-b90e-9964a6a164a9.jpg)![800_48_gradcam_cam](https://user-images.githubusercontent.com/52570733/130166545-923c68fe-6c9b-4c20-87dd-69f9190c1fca.jpg)![800_54_gradcam_cam](https://user-images.githubusercontent.com/52570733/130166582-21ffd81b-712e-44db-9610-b39d04314e0a.jpg)![800_63_gradcam_cam](https://user-images.githubusercontent.com/52570733/130166585-9822fb6d-6a7a-4e61-bfd0-bee41cfac793.jpg)

There seems to be something wrong with my results.  I was going to input one frame [3,224,224] to the method [https://github.com/jacobgil/pytorch-grad-cam](url). But it failed to the problem **"shape [-1,15,224,224] is invalid for input of size 150528"**, because the input tensor should be [-1, 3*5, 224, 224] in your model.

So I sampled the frames according to the strategy in your code for visualization in each segment. 5 consecutive frames [X1,X2,X3,X4,X5] was concated in each segment , and got the tensor [3x5,224,224]. Then, I repeated it 8 times to obtain the input tensor [3x5x8, 224, 224]. Finally, I got the CAM and multipled it onto X3.

Why is there an obvious CAM in each result frame? It seems to be different from the picture in your paper. Could you tell me what's wrong with my visualization?

**Comment by yztongzhan** [comment]
You can try this [repo](https://github.com/alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions) for visualization.
