### ISSUE TITLE
Confusion about the baseline 

### ISSUE THREAD

**Issue by wei666666** [MCG-NJU/TDN#37]
Hi, I'm very interested in your project. So, I'm coming back! In your ablation study, I found you mentioned **baseline** without S_TDM or L-TDM, only with shift operation in latter stages. So I reimplemented it. WOW~ It's amazing that the top1 accuracy reached 47.2% (45.2% in paper). I don't know what's wrong with the code. I would appreciate it if you could provide the code of baseline! (1845848350@qq.com)

Only two changes I made in your code:
**1.base_module.py**
![2021-09-15_221632](https://user-images.githubusercontent.com/52570733/133451157-9c870bf3-1879-47f0-968b-bf8163c9e533.jpg)
**2.tdn_net.py**
![2021-09-15_221917](https://user-images.githubusercontent.com/52570733/133451237-00e45af0-be0e-4ff3-9c63-4d1b29539228.jpg)

**Comment by yztongzhan** [comment]
Hi @wei666666, we have updated our camera ready version with stronger baseline.  You can check the baseline and any other result  in [arxiv](https://arxiv.org/abs/2012.10071) and [openaccess](https://openaccess.thecvf.com/content/CVPR2021/papers/Wang_TDN_Temporal_Difference_Networks_for_Efficient_Action_Recognition_CVPR_2021_paper.pdf). 
Thanks so much for sharing your interest in our TDN!
