### ISSUE TITLE
some confusions

### ISSUE THREAD

**Issue by Holmes-GU** [MCG-NJU/TDN#4]
hi,
 in tdn_net.py,
1. line 84: model = TDN_Net(resnet_model,resnet_model1,apha=0.5,belta=0.5)
why do you use two models of the same structures? I am very confused?

2. line 3 self.conv1_temp1 = list(resnet_model1.children())[0], the variable self.conv1_temp1 seems not to appear in the following cods, so what is this variable for?
Thank you.

**Comment by yztongzhan** [comment]
1. We use `resnet_model` for constructing the original RGB stream of S-TDM, while using `resnet_model1` for constructing the RGB difference stream of S-TDM.
2. The `self.conv1_temp1` in `tdn_net.py` might be redundant, we will check and remove it. Thanks for your suggestion.
