### ISSUE TITLE
dataset.py 'new_length'

### ISSUE THREAD

**Issue by zhanggj821** [MCG-NJU/TDN#42]
what does “new_length” mean in the dataset.py file, and what is the shape of a sample, sorry I'm a little confused to read the code

**Comment by venje-zhu** [comment]
都是中国人，我就不发英语了。new_length意思是连续序列的长度，比如从第5帧，往后采样new_length帧，符合作者文中提出的稀疏采样策略。至于样本的shape，我的数据集每个视频取50帧，segment设8，得到的shape为[120, 224, 224]，稀疏采样方法从50帧中取出40个连续new_length的序列，再以通道维度进行拼接。这是我的理解

**Comment by zhanggj821** [comment]
感谢回复你说的是对的，之后我认真看了一下。
