### ISSUE TITLE
About the reproduction of the hmdb51 dataset

### ISSUE THREAD

**Issue by Brasiletto** [MCG-NJU/TDN#45]
Hello, I would like to ask at which step is the fusion of rgb and flow to be performed when the hmdb51 data set is reproduced? Is it after pkl_to_results.py or?

**Comment by yztongzhan** [comment]
Hi @Brasiletto, thanks for your question. The input of our TDN is only the RGB frames and we didn't leverage the optical flow. You can refer our paper for more details.

**Comment by Brasiletto** [comment]
Ok, thank you!
