### ISSUE TITLE
Some confusion

### ISSUE THREAD

**Issue by wanlmq6165163** [MCG-NJU/TDN#46]
Please, how to implement the model collection, I did not find the relevant information in the code

**Comment by wanlmq6165163** [comment]
I mean the model ensemble, 8F+16F in result

**Comment by yztongzhan** [comment]
We have provided the code of model ensemble in `pkl_to_results.py`. You could put the prediction results of 8F+16F in the same folder and run `pkl_to_results.py` to generate the final result.
