### ISSUE TITLE
How does clip_index affect the sampling results?

### ISSUE THREAD

**Issue by Lilaoxie** [MCG-NJU/TDN#47]
When test kinetics, there is a argument _clip_index_. But in _dataset.py_, I find clip_index doesn't make any difference. So how do you control the distribution of input clips? Or did I neglect anything?

**Comment by yztongzhan** [comment]
Hi @Lilaoxie,  just neglect it. We generate the prediction results by randomly sampling one clip from the video and `clip_index` is used to distinguish the different results.
