### ISSUE TITLE
Question of setting of 'new_length' in dataset.py 

### ISSUE THREAD

**Issue by dy1998** [MCG-NJU/TDN#48]
Hello, I find that 'new_length' are always set as 5 in dataset.py. The following code in dataset.py confused me, as average_duration will get same result. Should new_length in else be set as 1? Hope for your kindly reply. Thank you.

```
        if not self.I3D_sample : # TSN uniformly sampling for TDN
            if((len(video_list) - self.new_length + 1) < self.num_segments):
                average_duration = (len(video_list) - 5 + 1) // (self.num_segments)
            else:
                average_duration = (len(video_list) - self.new_length + 1) // (self.num_segments)
```

**Comment by yztongzhan** [comment]
`new_length` is our mean the dense sampled 5 frames in one segment. S-TDM would compute the RGB difference between these frames to capture the approximate motion information in one temporal segment. Please refer to the Figure 3(a)  and
 Section 3.2 for more details.
