### ISSUE TITLE
Backward and forward in L-TDM module

### ISSUE THREAD

**Issue by troublecmd** [MCG-NJU/TDN#50]
Hello!
nice work you guys have done! 
I have a stupid question after reading paper and code carefully: 
What's the meaning of Backward and forward in L-TDM module ?

**Comment by yztongzhan** [comment]
Hi @troublecmd, thanks for your question!
Forwoard in L-TDM means F_{t+1} - F_{t}, Backward in L-TDM means F_{t} - F_{t+1}
