### ISSUE TITLE
可能的书写有误

### ISSUE THREAD

**Issue by Holmes-GU** [MCG-NJU/TDN#6]
你好：

opts/base_module.py 103、104行代码如下：
103 y_forward_smallscale4 = self.bn3_smallscale4(self.conv3_smallscale4(y_forward_smallscale4))
104 y_backward_smallscale4 = self.bn3_smallscale4(self.conv3_smallscale4(y_forward_smallscale4))
这个104行的输入变量y_forward_smallscale4是否有误呢？应该是y_backward_smallscale4吧？

**Comment by yztongzhan** [comment]
Thanks for your suggestion. We will fix this bug and update the model zoo very soon.

**Comment by Holmes-GU** [comment]
Hi, what does the term 'missing-alignment issue' in the paper mean?

**Comment by Holmes-GU** [comment]
> Thanks for your suggestion. We will fix this bug and update the model zoo very soon.

Hi, what does the term 'missing-alignment issue' in the paper mean?

**Comment by yztongzhan** [comment]
You can refer [STM](https://arxiv.org/abs/1908.02486)
