### ISSUE TITLE
训练数据集为什么不打乱？

### ISSUE THREAD

**Issue by Turing77** [MCG-NJU/TDN#62]
![image](https://user-images.githubusercontent.com/78059247/189868860-f9cbb4ec-18e3-467d-943e-6e99d2934b2e.png)
仔细查看了代码，数据集中关于训练集的dataloader，为什么不把数据集的顺序打乱，即shuffle=True

**Comment by yztongzhan** [comment]
Hi @Turing77! Thanks for your question! `shuffle=True` is set in `DistributedSampler` as default. 
https://github.com/MCG-NJU/TDN/blob/ba984a137320998b8d45b8236b7ec6612310851d/main.py#L101
You can check the implementation code of `DistributedSampler`
https://github.com/pytorch/pytorch/blob/7a9ab5c232f54430704456d18a22f99838489817/torch/utils/data/distributed.py#L62-L64

**Comment by Turing77** [comment]
yep! Thanks
