### ISSUE TITLE
about data input

### ISSUE THREAD

**Issue by sanwei111** [MCG-NJU/TDN#66]
def main():
    global args, best_prec1#best_prec1上面定义的：0
    args = parser.parse_args()

    torch.cuda.set_device(args.local_rank)
    torch.distributed.init_process_group(backend='nccl', init_method='env://')

    num_class, args.train_list, args.val_list, args.root_path, prefix = dataset_config.return_dataset(args.dataset, args.modality)

as it show（dataset_config.return_dataset），is the input belong to img or video？

**Comment by yztongzhan** [comment]
> is the input belong to img or video？

Frames are extracted from video on the fly. Please check the [Data Preparation](https://github.com/MCG-NJU/TDN#data-preparation).
