### ISSUE TITLE
Frames x Crops x Clips	

### ISSUE THREAD

**Issue by sanwei111** [MCG-NJU/TDN#67]
what ‘s the meaning of Frames x Crops x Clips？how to select pretrained model？

**Comment by yztongzhan** [comment]
`#Frame` means how many frames are input for model during the test phase.
`#Crop`means spatial crops (e.g., 3 for left/right/center crop).
`#Clip` means temporal clips (e.g., 10 means repeted temporal sampling ten clips with different start indices).
