### ISSUE TITLE
Confused about arguments

### ISSUE THREAD

**Issue by Fritskee** [MCG-NJU/TDN#9]
I'm currently running TDN on a personal dataset. Everything runs well. Initially I set `--num_segments=32` because I'm dealing with very fine grained actions. However,  this means that I need to set `--batch_size=4`, even when working on 2 Tesla V100 GPUs. 

I also ran a different experiment where I activate `--dense_sample`. What I cannot derive from the research paper is that when using "dense sampling" like I3D does, does `--num_segments` still matter, or can I set it to a very small number and receive the same results?

**Comment by yztongzhan** [comment]
Thanks @Fritskee! It is glad to know that our work facilitate your work. 
1. Although we don't konw the detail of your dataset, we recommend to set the '--num_segments=8/16' if the duration of videos in your dataset is similar to Kinetics and Something-Something (less than 10 minutes).
2. We didn't report the result of 'dense sampling' in our paper. From my perspective, 'dense sampling' like I3D does gets lower accuracy when perform 'one-clip and center-crop' testing scheme.

**Comment by Fritskee** [comment]
Hi @yztongzhan, thanks for the fast response!

1. My dataset is a self-created dataset. I have around 8000 clips that have a duration between 2 to 3 seconds. This means that there is a higher variance between frames. Therefore I set the `--num_segments` higher. I also experimented with TSM, where increasing the segments from 8 to 16 to 32 always showed a big top-1 accuracy boost. 
2. I'm aware there was no dense sampling mentioned. My question however remains: "Does using `--dense_sampling` make the setting of `--num_segments` superfluous?"

**Comment by yztongzhan** [comment]
Hi @Fritskee ! 
1. I think num_segments=16 in our `TDN` is enough for videos within 3 seconds. However, it would be better if num_segments=32 can boost the top-1 accuracy continuously.
2. The setting of `dense_sampling` is about the sampling **strategy** for the input video, while we use `sparse _sampling` like [TSN](https://arxiv.org/abs/1705.02953) for our experiments. The setting of `--num_segments` is about the  number of segments/frames which are sampled as the input of network.

**Comment by Fritskee** [comment]
@yztongzhan that is clear! Thanks a lot for the clarification! 

Regarding step 1: There's a pretty big difference between 16 and 32. So big that the increased inference time (and training time) is worth it for me. 

Anyway, thanks so much for the fast and clear responses! You're great!
